### ISSUE TITLE
Packages such as ProduKey and notepadplusplus

### ISSUE THREAD

**Issue by steve6375** [BahKoo/ChocolateStore#10]
These two packages only download and make .nupkg files but no setup.exe is downloaded/made.
I have only tried about 6 different packages so far.

**Comment by steve6375** [comment]
Also FireFox fails

**Comment by BahKoo** [comment]
For ProduKey and notepadplusplus use the following packages:

- http://chocolatey.org/api/v2/package/notepadplusplus.install/
- http://chocolatey.org/api/v2/package/produkey.install/

Note the ".install" at the end of the package name.  You need to use these versions because ChocolateStore does not currently support installing dependencies.

For firefox, the problem is that the nuget package composes the URL based on the locale. ChocolateStore does not currently support URLs that are pieced together in the script so unfortunately the firefox package will not currently work.

**Comment by steve6375** [comment]
Thanks for reply.
I can convert the notepadplusplus.instal and produkey packages OK
but  cinst produkey -source C:\DRIVERS\CHOCBOX says that it cannot find the package!
Other (non-install normal) packages work, but not these two install packages.
Any idea why cinst does not see them?
I have produkey.install.1.90.nupkg and produkey.install.1.90\produkey_setup.exe present, so cinst should see it and clist lists the apps.
???

**Comment by BahKoo** [comment]
To install, use the following commands:

- cinst notepadplusplus.install -source C:\DRIVERS\CHOCBOX
- cinst produkey.install -source C:\DRIVERS\CHOCBOX

**Comment by steve6375** [comment]
Thanks. I thought I tried that, but I tried again.
So they both fail for chocolatey-core.extension dependancy
So I also made an offline package for this and I think it is now working... :-)

**Comment by steve6375** [comment]
Yep - it works! Thanks for your great app (I will be adding it to my Easy2Boot SDI_CHOCO project so everyone can do offline app installs using any unmodified Windows 8/10 ISO).

**Comment by steve6375** [comment]
http://rmprepusb.blogspot.co.uk/2017/05/e2b-v193a-with-sdichoco-offline-package.html
